### ISSUE TITLE
안명호 대표님 시간 변경

### ISSUE THREAD

**Issue by ianychoi** [openstack-kr/2018#12]
@bluejayKR 

29일 발표시간을 오후1시부터 3시사이로  해주세요. 그 시간 이후에 제가 다른 일정이 있어서요 자료를 봤더니 오후 5시로 되어있던데 그 시간에는 다른 일정이 있어서 어렵습니다.

**Comment by bluejayA** [comment]
1시에서 3시 사이면, 다른 후원사들 발표만 있어서 애매하네요.

**Comment by bluejayA** [comment]
아토를 하나 내리고, 그 자리에 안명호대표님 넣었습니다. 
덕분에 유명환님은 맨 마지막 시간이지만 큰 방으로..

**Comment by ianychoi** [comment]
네 확인하였습니다: https://github.com/openstack-kr/2018/commit/492a3be8c686ec64156f097ea213376286751fa6 감사합니다
