### ISSUE TITLE
첫째날 키노트 수정 제안 

### ISSUE THREAD

**Issue by bluejayA** [openstack-kr/2018#2]
09:30-10:10
OpenStack Foundation Keynote
Jonathan Bryce, Executive Director - OpenStack Foundation
Lauren Sell, Vice President, Marketing and Community Services - OpenStack Foundation

위에 것을 아래처럼 바꿔주세요. 
그리고, 지금 TBD로 빼놓으신 20분은 없애면 될 것 같습니다. 

09:30-10:30 
Community Keynote
Jonathan Bryce, Executive Director - OpenStack Foundation
Lauren Sell, Vice President, Marketing and Community Services - OpenStack Foundation
Cloud Native Computing Foundation

**Comment by ianychoi** [comment]
Addressed by https://github.com/openstack-kr/2018/commit/4d4243c277cca41b4e30b16720566fb6753825a4 and others
